### ISSUE TITLE
[META] v3.0.0

### ISSUE THREAD

**Issue by taion** [ReactTraining/react-router#3611]
I'm setting this up as a meta-issue instead of a milestone to allow for more commentary and discussion. I'm going to close the originating issues and fold them into here for now, so we have a single issue on which to track things.

We're looking to cut a v3.0.0 soon, starting with PRs, to update dependencies, clean up deprecations from v2.x, and give users a path forward. I'm going to use this meta issue to list out the changes we're looking at making as we lead into release.

#### Requirements

These are the things that we must resolve before release:

- [x] Upgrade history dependency to v3 (#3515)
  - If we go ahead with https://github.com/ReactJSTraining/history/issues/322, we can probably drop the basename enhancer from the singleton histories, and let users use `withBasename`; given the removal of the automatic `<base href>` handling, adding the basename enhancer by default doesn't accomplish much
  - Should we force an initial `replace` to ensure that the initial location has a `key` when using browser history? cc @mjackson 
- [ ] Factor out context subscriber code into separate package (#3484)

#### Wishlist

These are the things that I'd personally like to get to before release, but am willing to discard if they cause too much schedule slip:

- [ ] Pull out `<LocationProvider>` component to inject down `location` as a prop into a separate component that just handles routing state management
  - Would allow better Redux integration, since the matcher could then consume `location` from the store
  - Might not be possible? How do we interact with `listenBefore`?
- [ ] Move matching logic into route objects (#2286)
  - Instead of having a top-level `matchRoutes` handler, instead have the router ask each route for whether it matches, and the matched routes
  - This would allow creating e.g. `<HapiRoute>`, to allow users to use route handlers with their choice of route matching
  - We could get a proper `routeParams` too, as each route would give its matched params (#3549)
- [x] Support returning promises from dynamic methods on routes (`getComponent`, `getChildRoutes`, &c.) (#3606)
  - This will allow better support for `System.import`
- [ ] Remove some edge case handling in default matching logic (with deprecations on v2.x)
  - Remove default support for nested absolute routes whose parents don't match (this can be handled in a custom-matching route) (#3172)
  - Change default pattern handling to path-to-regexp? This would make things easier to learn. We could warn on individual routes where the two matching algorithms give different results
- [ ] Split up client-side and server-side `match` helpers, since they don't do quite the same thing (#3290)
- [ ] Ensure that context subscriber handling works with context interceptors, as this will be needed for relative link support (but such support proper probably is too ambitious to squeeze into v3.0.0)

Well, please discuss.

The idea is to avoid any major breaking API changes – a working v2.x config should work with minor changes in v3.0.0. I'd like to take the opportunity to clean up cruft, but it's intentional that the wishlist is much longer than the list of requirements – I'm not going to be heartbroken if we can't get to some of these.

**Comment by taion** [comment]
Oops! Hit "submit" too quickly.

cc @reactjs/routing, @gaearon

The wishlist really is the wishlist. I'd like to get an `rc.1` with the upgraded history dep this week if possible, and the rest is just "as we have time before we hit a reasonable release deadline".

**Comment by taion** [comment]
BTW, "support async route leave hooks" is I think an explicit non-feature here. Users should leverage the custom confirmation prompt support in history to accomplish showing custom dialogs there.

**Comment by timdorr** [comment]
Regarding the history v3 upgrade, how do we want to handle that? Should we support both v2 and v3 histories? The API change around `location` is rather significant, so I know it would break a number of tools (`react-router-redux` most notably, but the fix is really simple).

**Comment by taion** [comment]
I want to support only v3.

My hope is that we go ahead with https://github.com/ReactJSTraining/history/issues/323.

That way, tools can explicitly check e.g. `history.API_LEVEL` to make sure they're getting something with the right semantics.

Otherwise they can stiff `history.getCurrentLocation`, but that's less ideal.

**Comment by timdorr** [comment]
I dunno. That kind of duck typing seems fine to me. You're doing a check for an API's existence, rather than relying on some number that could be a lie.

**Comment by taion** [comment]
Sorry, to clarify, that would be the case if I were just checking for the existence of `getCurrentLocation`.

What I'm really trying to assert there, though, is "`listen` doesn't immediately invoke the listener with the current location".

So the issue here isn't "duck typing" per se – it's "wrong duck typing"; the actual duck type asserting on the behavior of `listen` would be annoying to write.

**Comment by dmitriid** [comment]
For all that is good and holy, please make up your mind and unify the APIs for various routing-related parts.

`router` was in `context`, now it's deprecated and moved to a HOC.

Meanwhile `location` is still in `context`. Or is it? Oh. No. It's deprecated. 

Meanwhile my props are polluted with `history`, `route`, `routeParams`, `router` and `routes`. Just because, I guess. (Why are `routeParams` a separate prop and not available in `route`? Why aren't all these hidden in a single `router` object?)

Sooo... If I am to access the 0.x functionality exposed by `getParams`, `getRoutes`, `isActive` etc. I now have to:
- pass some stuff through props and make sure it's passed down an abritrarily long chain of components
- pass some stuff through context (or not? it's deprecated)  and make sure it's passed down an abritrarily long chain of components
- wrap some, or all, components with `withRouter` and make sure it's passed down an abritrarily long chain of components

...all the while making each and every upgrade to the new (sometimes minor, as with `2.4.0`) a *major* pain.
...all the while making `react-router` more and more cumbersome to work with or reason about

**Comment by umidbekkarimov** [comment]
What about methods that will manage query string only ?

```javascript
router.pushWithQuery = (query, merge = false) => { ... } 
router.replaceWithQuery = (query, merge = false) => { ... } 
```

So it will compose new `location` object with current `pathname` and given `query` params (or will merge current query params with given params if `merge` equals `true`)
___
First thought that i should create issue in [history](https://github.com/ReactJSTraining/history) repo, but then i realised that it's just helping functionality and should be implemented in `router`, not in `history`

**Comment by timdorr** [comment]
@dmitriid Router is still on context. We set up withRouter as an easier way to access it and to also ease and future API changes (we can change the implementation without you having to do anything). The removal of location is indicative of this need. We have heard rumblings of changing context to limit the returned child context to one property. 

Context is still considered a relatively unstable API in React, so our reliance on it as a public API is something that could bite us in the future. Hence, we abstracted it away. You're free to use it in the future, just with the understanding it might change upstream in the future. 

But code in 2.x without deprecation warnings will continue to work in 3.x. We take this part very seriously, since it has been a huge disruption in the past. The deprecations this time around will be more around cleanup and less flat-out changes. You won't have as much API volatility. 

@umidbekkarimov That kind of thing is better left to a middleware or history enhancer. Adding individual merging APIs for each location property is rather pedantic and creates a more confusing API. Once we have getCurrentLocation available, you can simple set a property to add in a query param.

**Comment by dmitriid** [comment]
@timdorr 

It's not only moving router to `withRouter`. It relates to _every part_ of the public API.

The router in the `withRouter` is passed in `props` passed to components. Which one should I use? The one in `props`? The one in `context` that is set up by someone in a component chain?

However, the router does not expose everything a developer needs.

For example, it has the `isActive` method. Aaaand it's basically useless. Because I need to pass a path to it. Where can I get it from? From the `route` in `props`? Or from `location` in `context`? Or from both? Upgrade docs state that ["Accessing this.context.history, this.context.location, and this.context.route are all deprecated"](https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md), so it's `props.*` then?

I need to find out route params. One would think they (and the `isActive` method come to think of it) would be exposed in the `this.props.route` object. Nope, they are not. `this.context.location` object? Nope. Oh, it's `this.props.routeParams`.

And these things keep piling onto each other. The API is split across numerous moving parts that have to be set up and tracked separately from each other in various ways:
- you need to wrap components with `withRouter` in one case
- you need to track which props you pass down to children in another case
- you need to track if there's context and pass it along to children in a third case

Even though all these parts are supposed to work in conjunction with each other.

So my plea is: please unify all these into a coherent API that can be used _consistently in the same manner_ across components. `3.0.0` is a major release, so you can release a backwards incompatible API with deprecation warnings for the 2.x API.

Right now it's almost impossible to even reason about `react-router` API: where do these things that I need to work with come from? Context? Props? Both of them? Do I wrap a class in a HOC? Do I pass props? Do I pass contexts? The docs say some things are deprecated and some are not, some are recommended and some are not. The recommended things cannot be used effectively in isolation from non-recommended things in certain scenarios or expose only partial functionality. etc. etc. etc.

**Comment by dmitriid** [comment]
Argh. It was too much ranting, not enough coherent thinking.

Basically what it comes down to is: can you use the API using only one of the possible approaches?

- can you use `router` API using only `props` that are passed to a component (use history, find if current route is active, etc.)? That is, without the need to wrap a component in a HOC or without the use of contexts.
- can you use APIs exposed by `props` wihtout the props? That is, can you retrieve the current route, route params etc. while only using `withRouter` or `context`?
- `context` API is unstable/deprecated so the third question is out of question :)

If any answer is "no", then that particular API is incomplete/inconsistent and should be made complete/consistent. Otherwise it creates unnecessary friction and future upgrade pains.

Unfortunately, currently the answer is "no", and my suggestion is to make it a "yes" in 3.0.0

**Comment by taion** [comment]
For v3.0.0-alpha.1, and future releases:

1. For a route component, all the props you need are passed in; otherwise, you can pass down the relevant props manually if you need to
2. If you have a nested component that doesn't immediately have props available, you can use `withRouter` to make those props available
3. If you don't want the overhead of an HoC and are comfortable with context, you can use `context.router`, which also provides the other objects necessary for routing

The answer is _not_ "no".

BTW, I'm going to be moderating this thread closely to keep the length manageable. We want this to be an approachable list of changes where users can track what's happening, why, and discuss specific features – nothing personal, but I'd like to limit how much this discussion gets sidetracked.

**Comment by taion** [comment]
@umidbekkarimov @timdorr 

You can merge queries yourself quite easily with the `location` object, and push/replace using object destructuring. You probably shouldn't use `history.getCurrentLocation`, since it goes off and reads from the browser APIs – just use the existing `location` object. The whole point of the `push` and `replace` API is to let you do

```js
history.push({ ...location, query: newQuery })
history.push({ ...location, query: { ...query, ...newQuery } })
```

We intentionally don't offer lower-level primitives here, because the existing semantics are already good enough.

**Comment by dmitriid** [comment]
@taion 

Just checked with 2.4.0:

```jsx

<Route path="/" component={X}>
</Route>


const X = (props) => {
  return Y
}

const Y = withRouter(SomeComponent)
```

`X`'s `props` contain the following:
- `history`
- `location`
- `route`
- `routeParams`
- `routes`

`Y`'s `props` contain the following:
- `router`

Which obvious, since the only prop that `withRouter` [passes in](https://github.com/reactjs/react-router/blob/master/modules/withRouter.js#L13) is `router`

So, no, the answer is *no*. As a developer, I cannot rely on anything to pass anything to you. Please make this consistent.

**Comment by taion** [comment]
> For 3.0.0-alpha.1

**Comment by dmitriid** [comment]
Ah! Totally missed that one. Then I'm entirely content :) Thank you!

**Comment by taion** [comment]
I'm condensing and clearing out some earlier comments:

@dmitriid notes that the `withRouter` API doesn't match the API for route components in 2.x. This is resolved in 3.0.0-alpha.1, where `withRouter` also injects `routes`, `params`, and `location`. Thus, the injected props to a `withRouter` component mostly matches what's available to a route component, net of `route`, which we would need extra work to be able to inject.

@umidbekkarimov mentions `push` handlers with special query support. We're currently not planning on implementing something along those lines, because the current `push` API is already quite good for merging and overriding queries:

```js
router.push({ ...location, query: newQuery })
router.push({ ...location, query: { ...query, ...newQuery } })
```

**Comment by taion** [comment]
For history v3, I think the right way to go forward is to do something like this check: https://github.com/reactjs/react-router/blob/v2.5.2/modules/Router.js#L18-L21

The user-facing APIs are largely identical, so we'll just force the user to supply a v3 history, and throw if the history does not support `getCurrentLocation`.

**Comment by jedwards1211** [comment]
@taion have you thought about supporting promises returned from `component`, `childRoutes`, etc instead of the getters?

**Comment by timdorr** [comment]
I was going to PR something around that soon. It shouldn't be hard, just change things like [this call to `getComponents` to check for a Promise](https://github.com/reactjs/react-router/blob/master/modules/getComponents.js#L19).

**Comment by donaldpipowitch** [comment]
I have the feeling that async `onEnter` isn't working as expected in general (imho).

Say I have a `route-a` rendering `ComponentA` and a `route-b` rendering `ComponentB` and switching between both routes takes 2 seconds.

1. When I switch from `route-a` to `route-b` I wouldn't expect that the URL changes immediately, but only if I call the `callback` inside `onEnter`. That way I can abort the transition if an error happens or redirect to a different route without changing the URL to a route which is never rendered.

2. When I switch from `route-a` to `route-b` and I go _back_ in my browser history after 1 second, I see the URL for `route-a`, but `ComponentB` will be rendered. (This is basically a different scenario for issue #3476.)

3. Animations don't behave as expected (explained [here](https://github.com/reactjs/react-router/issues/17#issuecomment-238490681)).

It would be nice if this can be addressed in v3 and if this works as intended, it would be nice if the docs could explain this behaviour.

**Comment by yormi** [comment]
I don't know if it can be useful for you guys but since 3.0.0-alpha.2, the first click on a Link when the app is loaded change the URL but does not render the component associated to the new URL.

After that first click, everything works fine though.

I use react-router-redux, I don't know if it changes something...

**Comment by taion** [comment]
Quick update for anyone that cares – main blocker for moving to an actual RC is figuring out how to display loading status when doing async routing, as that's become a major issue for us at work.

Need to figure out the appropriate API here, and I don't think we should commit to an RC until we've figured that out (would ideally like to avoid that sort of API change after we hit RC).

**Comment by jedwards1211** [comment]
@taion some thoughts about loading status:

These days I prefer doing async loading in a userland `component` (that displays loading status) instead of using an async `getComponent`.  IMO `getComponent` isn't really the best place to do async loading, and it would be better to deprecate it and encourage users to pass in a `component` that does the async loading (and status display if they want).

On the other hand, `getChildRoutes` is quite different.  I have a userland solution for displaying loading status while async loading child routes too, but it involves several messy hacks.  So I think a good API for returning a temporary loading route while the real child routes are being loaded is worth the effort (and I'm guessing the same would be the case for `getIndexRoute`, though I haven't ever needed to use it).

**Comment by taion** [comment]
Doing async loading in the component is tempting but suboptimal in the case of nested routes – it forces waterfalled loads, as we've discussed on other issues.

I consider that compromise to be unacceptable. Users _should not_ do async loading as part of the render cycle.

**Comment by jedwards1211** [comment]
Oh man, I keep forgetting about that.  How awkward...

**Comment by donaldpipowitch** [comment]
Maybe this is an interesting point for an upgrade guide:
- Since react-router v3 uses history v3 `hashHistory` has no [`_k`](https://github.com/reactjs/react-router/blob/master/docs/guides/Histories.md#what-is-that-_kckuvup-junk-in-the-url) by default, if no `state` is used (see mjackson/history#163).
- Some libraries like taion/react-router-scroll need that key to work correctly, even if `state` isn't used. (Maybe this is a code smell in itself...?)

I'm not really sure currently what is the best way to bring back `_k`. I guess I need to create a custom `hashHistory`...?

**Comment by buzinas** [comment]
I would like to have two other hooks: `onBeforeEnter` and `onBeforeLeave`. I needed those hooks in two projects already, and I'm always hacking something to make this behavior possible.

When entering a route, the general idea is:
- If there is no `onBeforeEnter` hook set, we keep the current behavior
- If it's set, it is expected to return a `Boolean`.
  - If its return value is truthy, we keep the current behavior
  - If its return value is falsy, then we don't call the `onEnter` hook and we cancel the current behavior.

The `onBeforeLeave` hook would work in a similar way when leaving a route.

**Comment by taion** [comment]
We're not planning on adding additional route hooks at the moment. The API surface area is too large there, and many of the existing use cases are better handled at the component level.

While we don't plan on deprecating any existing route hooks in v3.x, we are unlikely to add any new ones. The set of use cases there are not broad enough to warrant the increased API surface area.

**Comment by zdila** [comment]
Meanwhile history 4.0.0 has been released ;-)

**Comment by killroy42** [comment]
But how does it work? :(

**Comment by timdorr** [comment]
history 4.0 will correspond with react-router 4.0, which is being worked on separately from 3.0. This is more of an evolutionary change, whereas 4.0 will be more revolutionary (and hence history 4.0 is a *very* big shift).

**Comment by killroy42** [comment]
I'm downgrading to 2.8.0. It seems that the 4.x release isn't official. This site https://react-router-website-uxmsaeusnn.now.sh/quick-start looks kinda dodge and the API is a bit of a mess now, aparently... I supose I upgraded pre-maturely. but a -beta or -rc tag would be great.

**Comment by timdorr** [comment]
It's a pre-release, hence the - after the version. It's "official" in the sense that @ryanflorence released it. It has an entirely new design, so there isn't really a defined upgrade path just yet. You should give it a try on a new application, rather than trying to shoehorn it into an existing app with routing in it.

**Comment by killroy42** [comment]
Understood. I downgraded. Been optimistically updating a lot of things today, Not sure if I spend more time chasing bugs already fixed in more recent releases or new bugs introduced by more recent releases ;)

**Comment by CrocoDillon** [comment]
I know that this is about v3 but since we're talking about v4 already anyway, is there any place where I can find the reasoning behind the changes in v4? It seems like everything has changed and it would help me (and I'm sure others) to know why.

**Comment by ryanflorence** [comment]
Yeah we'll have a write up soon. Short story is, React Router had too much API and got way too far from being a "React Router" but was rather a "Router for React". It wasn't composable, and it wasn't declarative. So we made it composable and declarative.

**Comment by jochenberger** [comment]
On a side note, https://react-router-website-uxmsaeusnn.now.sh/ contains a dead link ("hosted on GitHub" points to https://github.com/reactjstraining/react-router).

**Comment by timdorr** [comment]
Just merged in `master` to `next` and resolved some conflicts there. I think we're good to go up to beta now. Most other things in here can be addressed in a minor.

**Comment by timdorr** [comment]
3.0.0-beta.1 is out! https://github.com/ReactTraining/react-router/releases/tag/v3.0.0-beta.1

`npm install react-router@beta` to get it!

**Comment by jedwards1211** [comment]
I'm not on twitter, so I'm posting here, v4 looks awesome!  I read some of the examples and rationale today, and the new API makes so much sense.  Reminds me how some of my own component designs have evolved as I've gotten more experienced using React.  Can't wait to use v4!

**Comment by jflayhart** [comment]
Really would love to see efforts for #2286. I am of the opinion, however, that this is a bug with react-router and we should be able to specify if an `:id` param is alphanumeric or of type number. It took me some time to debug these routing issues until I found this ticket.

**Comment by timdorr** [comment]
@jflayhart 4.0 uses path-to-regexp, which lets you do that exact kind of thing.

Are we good to go on 3.0? #3852 is the only thing outstanding, and that can be done in a minor later.

**Comment by johnnyreilly** [comment]
Is 3.0 still going to be released then? I kind of assumed you were going to jump straight to 4. That's not the case?

**Comment by timdorr** [comment]
2.x/3.x will be maintained indefinitely, for those that don't want or aren't able to upgrade to 4.0. 3.0 rolls up some deprecation removals and a few improvements/fixes, but is otherwise a fairly boring release :smile:

**Comment by johnnyreilly** [comment]
That's actually great news.  I know the project I'm working on is fairly large / complex and the likelihood of getting a thumbs up to go to 4.0 may well be a long time coming...  So thanks 👍 😄

**Comment by taion** [comment]
I'm not aware of any blockers.

**Comment by timdorr** [comment]
We're live! https://github.com/ReactTraining/react-router/releases/tag/v3.0.0
