### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mjackson** [ReactTraining/react-router#6885]
This issue is a high-level roadmap for all work on the 5.x branch. The goal is to provide:

- a transparent process for the priority of a given piece of work
- an expected release version

The goal is not to discuss specific release dates, though some of that may happen.

This list is by no means exhaustive and will change from time to time as new issues are opened and PRs are merged.

### ~~4.4~~ [5.0](https://github.com/ReactTraining/react-router/releases/tag/v5.0.0)

- [x] No warnings in React 16's `<StrictMode>`
  - [x] Stop using legacy context
  - [x] Remove all usage of `componentWill*` methods
- [x] Single-file builds
  - [x] Add warnings for deprecated `react-router-dom/Link`-style imports (5bde02b80b68155ba84afeb4f424cb2e7bacde43)
  - [x] Add warnings about using 2 different builds (#6361)
  - [x] Make tree-shaking actually work as expected (#6464)
- [x] Fully automated releases from CI

### [5.1](https://github.com/ReactTraining/react-router/releases/tag/v5.1.0)

- [x] Add useParams, useLocation, useHistory, and useRouteMatch hooks (d6224d6)
- [x] Add support for forwardRef in <Link> (b5528ed)
- [x] Add support for functions in `<Link to>` and `<NavLink to>` (#5331, #5368)
- [x] Add `<Link component>` API (#5437)

### [5.1.1](https://github.com/ReactTraining/react-router/releases/tag/v5.1.1)

- [x] Fix issue with useParams reading from null object (#6940)
- [x] Fix regression passing `ref` to functional components in React <= 16.2 (#6934)
- [x] Fix regression passing empty string to `matchPath` (#6941)

### [5.1.2](https://github.com/ReactTraining/react-router/releases/tag/v5.1.2)

- [x] Fix lingering `<Link ref>` error on React 15 (#6954)

### 5.2

- [ ] Stop `push`ing to the history stack on link clicks when location is the same (#5362)

### Backlog

- [ ] Add TypeScript and Flow types
- [ ] Define scope of react-router-config
- [ ] Use Suspense to allow cancelling navigation when the user follows another `<Link>` and the first one is still fetching- [ ] Add focus management APIs (#5210, #6449, #6454)
- [ ] Isolate build artifacts to a single `build` directory
- [ ] Add a build for react-router-native so we can e.g. exclude `__DEV__` code like we do in other package builds
- [ ] Move `react-router-dom` to `react-router/dom` to avoid context mismatch issues (#6755)
